In [1]:
# reshaping and operations 
import numpy as np
a = np.array([10, 20, 30, 40, 50])

print("First element:", a[0])
print("Last element:", a[-1])
print("Slice 1–3:", a[1:4])

# 2D array
m = np.arange(1, 10).reshape(3,3)
print("Matrix:\n", m)

print("Element (row 0, col 1):", m[0,1])
print("Second row:", m[1,:])
print("Third column:", m[:,2])


First element: 10
Last element: 50
Slice 1–3: [20 30 40]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element (row 0, col 1): 2
Second row: [4 5 6]
Third column: [3 6 9]
