In [ ]:
# array creation methods 
# From list
import numpy as np
arr = np.array([10, 20, 30])
# Range
arr2 = np.arange(0, 10, 2)
# Evenly spaced
arr3 = np.linspace(0, 1, 5)
# Zeros & ones
zeros = np.zeros((2,3))
ones = np.ones((3,2))
# Random
rand = np.random.rand(3,3)
rint = np.random.randint(1, 10, size=(2,4))
print("Array:", arr)
print("Range:", arr2)
print("Linspace:", arr3)
print("Zeros:\n", zeros)
print("Random integers:\n", rint)


Array: [10 20 30]
Range: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Random integers:
 [[7 3 7 3]
 [9 8 1 4]]
