In [12]:
# reshaping and operations 
import numpy as np

arr = np.arange(1, 13)
matrix = arr.reshape(3,4)
print("Matrix:\n", matrix)

# Transpose
print("Transpose:\n", matrix.T)

# Stats
print("Sum:", matrix.sum())
print("Mean:", matrix.mean())
print("Standard Deviation:", matrix.std())

# Element-wise operations
print("Matrix * 2:\n", matrix * 2)
print("Matrix + 5:\n", matrix + 5)


Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Sum: 78
Mean: 6.5
Standard Deviation: 3.452052529534663
Matrix * 2:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Matrix + 5:
 [[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
